# Adding tests to a project helps validate that your models are working correctly.

version: 2

models:
  - name: customers
    columns:
      - name: customer_id
        tests:
          - unique
          - not_null
      - name: first_name
          tests:
            - unique
      
